'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class categoria_tb
    Public Property idCategoria As Integer
    Public Property NomeCategoria As String
    Public Property DescricaoCategoria As String
    Public Property ControleStock As String

    Public Overridable Property produtos_tb As ICollection(Of produtos_tb) = New HashSet(Of produtos_tb)

End Class
