'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class detalhes_entradaprodu
    Public Property idDetalhes_EntradaProdu As Integer
    Public Property Produto_Preco As Nullable(Of Decimal)
    Public Property Produto_Quantidade As Nullable(Of Integer)
    Public Property Produto_Total As Nullable(Of Decimal)
    Public Property idEntradaProduto As Nullable(Of Integer)
    Public Property idProduto As Nullable(Of Integer)
    Public Property Produto_Nome As String
    Public Property ValorCompra As Nullable(Of Decimal)
    Public Property ValorVenda As Nullable(Of Decimal)
    Public Property detalhes_entradaproducol As String

    Public Overridable Property entradaproduto_tb As entradaproduto_tb
    Public Overridable Property produtos_tb As produtos_tb

End Class
