'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class detalhes_produto
    Public Property idDetalhes As Integer
    Public Property Prod_Preco As Nullable(Of Decimal)
    Public Property Prod_Qty As Nullable(Of Integer)
    Public Property Pro_Tt As Nullable(Of Decimal)
    Public Property idVenda As Nullable(Of Integer)
    Public Property idProd As Nullable(Of Integer)
    Public Property Prod_Referencia As String
    Public Property ProdutoNome As String

    Public Overridable Property produtos_tb As produtos_tb
    Public Overridable Property venda_tb As venda_tb

End Class
