'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class empresa_tb
    Public Property idEmpresa As Integer
    Public Property NomeEmpresa As String
    Public Property NuitEmpresa As String
    Public Property ContactoEmpresa As String
    Public Property EmailEmpresa As String
    Public Property LogoTipo As Byte()
    Public Property LocalizacaoEmpresa As String
    Public Property FileName As String

End Class
