'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class entradaproduto_tb
    Public Property idEntradaProduto As Integer
    Public Property idFornecedor As Nullable(Of Integer)
    Public Property DataEntrada As Nullable(Of Date)
    Public Property DataRecebimento As Nullable(Of Date)
    Public Property ValorRequizicao As Nullable(Of Decimal)
    Public Property Comentario As String

    Public Overridable Property detalhes_entradaprodu As ICollection(Of detalhes_entradaprodu) = New HashSet(Of detalhes_entradaprodu)
    Public Overridable Property fonecedor_tb As fonecedor_tb

End Class
