'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class fonecedor_tb
    Public Property idFonecedor_tb As Integer
    Public Property NomeFonecedor As String
    Public Property Nuit As String
    Public Property Contacto As String
    Public Property Email As String
    Public Property Data_Fornecedor As String
    Public Property FonecedorCod As String

    Public Overridable Property entradaproduto_tb As ICollection(Of entradaproduto_tb) = New HashSet(Of entradaproduto_tb)

End Class
