'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tipousuario_tb
    Public Property idTipoUsuario As Integer
    Public Property NomeTipoUsuario As String
    Public Property NivelPermissao As String

    Public Overridable Property usuario_tb As ICollection(Of usuario_tb) = New HashSet(Of usuario_tb)

End Class
