'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class usuario_tb
    Public Property idUsuario As Integer
    Public Property NomeCompleto As String
    Public Property DataNascimento As Nullable(Of Date)
    Public Property NomeUsuario As String
    Public Property SenhaUsuario As String
    Public Property idTipoUsuario As Nullable(Of Integer)

    Public Overridable Property tipousuario_tb As tipousuario_tb
    Public Overridable Property venda_tb As ICollection(Of venda_tb) = New HashSet(Of venda_tb)

End Class
